namespace XD_DBDW_Server
{
    partial class UI_FrequencySpectrum
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Mitov.PlotLab.ScopeChannel scopeChannel2 = new Mitov.PlotLab.ScopeChannel();
            Mitov.PlotLab.ScopePoints scopePoints2 = new Mitov.PlotLab.ScopePoints();
            Vcl.VclPen vclPen7 = new Vcl.VclPen();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UI_FrequencySpectrum));
            Mitov.PlotLab.ScopeDataView scopeDataView2 = new Mitov.PlotLab.ScopeDataView();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground6 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings6 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen8 = new Vcl.VclPen();
            Mitov.PlotLab.DataDisplayHighlighting dataDisplayHighlighting2 = new Mitov.PlotLab.DataDisplayHighlighting();
            Mitov.PlotLab.ChannelItemHighlighting channelItemHighlighting3 = new Mitov.PlotLab.ChannelItemHighlighting();
            Mitov.PlotLab.ChannelItemHighlighting channelItemHighlighting4 = new Mitov.PlotLab.ChannelItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting7 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting8 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting9 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting10 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting11 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.ChannelMouseHitPoint channelMouseHitPoint2 = new Mitov.PlotLab.ChannelMouseHitPoint();
            Mitov.SignalLab.OptionalLabel optionalLabel2 = new Mitov.SignalLab.OptionalLabel();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting12 = new Mitov.PlotLab.DisplayItemHighlighting();
            OpenWire.Proxy.PinList pinList3 = new OpenWire.Proxy.PinList();
            Mitov.PlotLab.ScopeLegendView scopeLegendView2 = new Mitov.PlotLab.ScopeLegendView();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground7 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.LegendViewButtonSettings legendViewButtonSettings2 = new Mitov.PlotLab.LegendViewButtonSettings();
            Mitov.PlotLab.LegendGroup legendGroup9 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel9 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup10 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel10 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup11 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel11 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup12 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel12 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup13 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel13 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup14 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel14 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup15 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel15 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.DisplayViewSize displayViewSize5 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.LegendGroup legendGroup16 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel16 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.DisplayTitle displayTitle2 = new Mitov.PlotLab.DisplayTitle();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground8 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.DisplayViewSize displayViewSize6 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayToolBar displayToolBar2 = new Mitov.PlotLab.DisplayToolBar();
            Mitov.PlotLab.DisplayToolBarButtons displayToolBarButtons2 = new Mitov.PlotLab.DisplayToolBarButtons();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton21 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton22 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton23 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton24 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton25 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton26 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton27 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton28 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton29 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton30 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton31 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton32 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.ToolBarPosition toolBarPosition2 = new Mitov.PlotLab.ToolBarPosition();
            Mitov.PlotLab.DisplayTrails displayTrails2 = new Mitov.PlotLab.DisplayTrails();
            Mitov.PlotLab.ScopeXAxis scopeXAxis2 = new Mitov.PlotLab.ScopeXAxis();
            Mitov.PlotLab.DisplayTitleLabel displayTitleLabel3 = new Mitov.PlotLab.DisplayTitleLabel();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground9 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.ViewButtonSettings viewButtonSettings3 = new Mitov.PlotLab.ViewButtonSettings();
            Mitov.PlotLab.DisplayAxisCursorSettings displayAxisCursorSettings3 = new Mitov.PlotLab.DisplayAxisCursorSettings();
            Mitov.PlotLab.DisplayGridDirectionalLinesSettings displayGridDirectionalLinesSettings3 = new Mitov.PlotLab.DisplayGridDirectionalLinesSettings();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings7 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen9 = new Vcl.VclPen();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings8 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen10 = new Vcl.VclPen();
            Mitov.PlotLab.AxisFormat axisFormat3 = new Mitov.PlotLab.AxisFormat();
            Mitov.PlotLab.MajorTicks majorTicks3 = new Mitov.PlotLab.MajorTicks();
            Mitov.PlotLab.TicksStart ticksStart3 = new Mitov.PlotLab.TicksStart();
            Mitov.PlotLab.MaxAxisValue maxAxisValue3 = new Mitov.PlotLab.MaxAxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange7 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue13 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue14 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue5 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.ScopeMaxSample scopeMaxSample2 = new Mitov.PlotLab.ScopeMaxSample();
            Mitov.PlotLab.AxisValue axisValue3 = new Mitov.PlotLab.AxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange8 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue15 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue16 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue6 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.MinorTicks minorTicks3 = new Mitov.PlotLab.MinorTicks();
            Mitov.PlotLab.AxisToolBar axisToolBar3 = new Mitov.PlotLab.AxisToolBar();
            Mitov.PlotLab.AxisToolBarButtons axisToolBarButtons3 = new Mitov.PlotLab.AxisToolBarButtons();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton33 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton34 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton35 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton36 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.ScopeXAxisUnitScale scopeXAxisUnitScale2 = new Mitov.PlotLab.ScopeXAxisUnitScale();
            Mitov.PlotLab.DisplayViewSize displayViewSize7 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayAxisZoom displayAxisZoom3 = new Mitov.PlotLab.DisplayAxisZoom();
            Mitov.PlotLab.DisplayValueRange displayValueRange9 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue17 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue18 = new Mitov.PlotLab.DisplayOptionalValue();
            OpenWire.Proxy.StatePin statePin3 = new OpenWire.Proxy.StatePin();
            OpenWire.Proxy.PinList pinList4 = new OpenWire.Proxy.PinList();
            Mitov.PlotLab.ScopeYAxis scopeYAxis2 = new Mitov.PlotLab.ScopeYAxis();
            Mitov.PlotLab.ScopeAutoScaling scopeAutoScaling2 = new Mitov.PlotLab.ScopeAutoScaling();
            Mitov.PlotLab.ScopeAutoScalingSpace scopeAutoScalingSpace3 = new Mitov.PlotLab.ScopeAutoScalingSpace();
            Mitov.PlotLab.ScopeAutoScalingSpace scopeAutoScalingSpace4 = new Mitov.PlotLab.ScopeAutoScalingSpace();
            Mitov.PlotLab.DisplayTitleLabel displayTitleLabel4 = new Mitov.PlotLab.DisplayTitleLabel();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground10 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.ViewButtonSettings viewButtonSettings4 = new Mitov.PlotLab.ViewButtonSettings();
            Mitov.PlotLab.DisplayAxisCursorSettings displayAxisCursorSettings4 = new Mitov.PlotLab.DisplayAxisCursorSettings();
            Mitov.PlotLab.DisplayGridDirectionalLinesSettings displayGridDirectionalLinesSettings4 = new Mitov.PlotLab.DisplayGridDirectionalLinesSettings();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings9 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen11 = new Vcl.VclPen();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings10 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen12 = new Vcl.VclPen();
            Mitov.PlotLab.AxisFormat axisFormat4 = new Mitov.PlotLab.AxisFormat();
            Mitov.PlotLab.MajorTicks majorTicks4 = new Mitov.PlotLab.MajorTicks();
            Mitov.PlotLab.TicksStart ticksStart4 = new Mitov.PlotLab.TicksStart();
            Mitov.PlotLab.MaxAxisValue maxAxisValue4 = new Mitov.PlotLab.MaxAxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange10 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue19 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue20 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue7 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.AxisValue axisValue4 = new Mitov.PlotLab.AxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange11 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue21 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue22 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue8 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.MinorTicks minorTicks4 = new Mitov.PlotLab.MinorTicks();
            Mitov.PlotLab.AxisToolBar axisToolBar4 = new Mitov.PlotLab.AxisToolBar();
            Mitov.PlotLab.AxisToolBarButtons axisToolBarButtons4 = new Mitov.PlotLab.AxisToolBarButtons();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton37 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton38 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton39 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton40 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayViewSize displayViewSize8 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayAxisZoom displayAxisZoom4 = new Mitov.PlotLab.DisplayAxisZoom();
            Mitov.PlotLab.DisplayValueRange displayValueRange12 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue23 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue24 = new Mitov.PlotLab.DisplayOptionalValue();
            OpenWire.Proxy.StatePin statePin4 = new OpenWire.Proxy.StatePin();
            Mitov.PlotLab.DisplayZoom displayZoom2 = new Mitov.PlotLab.DisplayZoom();
            this.panelControl1 = new DevExpress.XtraEditors.PanelControl();
            this.scope1 = new Mitov.PlotLab.Scope(this.components);
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.button1 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.panelControl1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.scope1)).BeginInit();
            this.SuspendLayout();
            // 
            // panelControl1
            // 
            this.panelControl1.Controls.Add(this.scope1);
            this.panelControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelControl1.Location = new System.Drawing.Point(0, 0);
            this.panelControl1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.panelControl1.Name = "panelControl1";
            this.panelControl1.Size = new System.Drawing.Size(766, 395);
            this.panelControl1.TabIndex = 0;
            // 
            // scope1
            // 
            this.scope1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeChannel2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeChannel2.MouseCursor = System.Windows.Forms.Cursors.Default;
            scopeChannel2.Name = "Channel0";
            scopePoints2.Brush = new Vcl.VclBrush(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), 0);
            vclPen7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            vclPen7.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen7.InternalData")));
            scopePoints2.Pen = vclPen7;
            scopePoints2.Size = ((uint)(3u));
            scopeChannel2.Points = scopePoints2;
            scopeChannel2.XAxisIndex = 0;
            scopeChannel2.YAxisIndex = 0;
            this.scope1.Channels.AddRange(new Mitov.PlotLab.ScopeChannel[] {
            scopeChannel2});
            displayViewBackground6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeDataView2.Background = displayViewBackground6;
            vclPen8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            vclPen8.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen8.InternalData")));
            displayGridLineSettings6.Pen = vclPen8;
            scopeDataView2.Border = displayGridLineSettings6;
            this.scope1.DataView = scopeDataView2;
            this.scope1.Dock = System.Windows.Forms.DockStyle.Fill;
            channelItemHighlighting3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataDisplayHighlighting2.ChannelLinks = channelItemHighlighting3;
            channelItemHighlighting4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataDisplayHighlighting2.Channels = channelItemHighlighting4;
            displayItemHighlighting7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataDisplayHighlighting2.CursorLinks = displayItemHighlighting7;
            displayItemHighlighting8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataDisplayHighlighting2.Cursors = displayItemHighlighting8;
            displayItemHighlighting9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataDisplayHighlighting2.Ellipses = displayItemHighlighting9;
            displayItemHighlighting10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataDisplayHighlighting2.Labels = displayItemHighlighting10;
            displayItemHighlighting11.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataDisplayHighlighting2.Markers = displayItemHighlighting11;
            channelMouseHitPoint2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            optionalLabel2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 0);
            channelMouseHitPoint2.PointLabel = optionalLabel2;
            dataDisplayHighlighting2.MouseHitPoint = channelMouseHitPoint2;
            displayItemHighlighting12.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataDisplayHighlighting2.Zones = displayItemHighlighting12;
            this.scope1.Highlighting = dataDisplayHighlighting2;
            this.scope1.InputPins = pinList3;
            this.scope1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scope1.InternalData")));
            displayViewBackground7.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeLegendView2.Background = displayViewBackground7;
            legendViewButtonSettings2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.Cursor = System.Windows.Forms.Cursors.Default;
            legendViewButtonSettings2.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings2.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeLegendView2.Buttons = legendViewButtonSettings2;
            displayLabel9.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup9.Caption = displayLabel9;
            legendGroup9.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.ChannelLinks = legendGroup9;
            displayLabel10.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup10.Caption = displayLabel10;
            legendGroup10.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.Channels = legendGroup10;
            displayLabel11.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup11.Caption = displayLabel11;
            legendGroup11.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.CursorLinks = legendGroup11;
            displayLabel12.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup12.Caption = displayLabel12;
            legendGroup12.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.Cursors = legendGroup12;
            displayLabel13.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup13.Caption = displayLabel13;
            legendGroup13.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.Ellipses = legendGroup13;
            scopeLegendView2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 0);
            scopeLegendView2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeLegendView2.InternalData")));
            displayLabel14.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup14.Caption = displayLabel14;
            legendGroup14.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.Labels = legendGroup14;
            displayLabel15.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup15.Caption = displayLabel15;
            legendGroup15.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.MarkerGroups = legendGroup15;
            displayViewSize5.Size = ((uint)(100u));
            scopeLegendView2.ViewSize = displayViewSize5;
            displayLabel16.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            legendGroup16.Caption = displayLabel16;
            legendGroup16.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView2.Zones = legendGroup16;
            this.scope1.Legend = scopeLegendView2;
            this.scope1.Location = new System.Drawing.Point(2, 2);
            this.scope1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.scope1.Name = "scope1";
            this.scope1.RefreshInterval = ((uint)(100u));
            this.scope1.Size = new System.Drawing.Size(762, 391);
            this.scope1.SizeLimit = ((uint)(0u));
            this.scope1.TabIndex = 0;
            this.scope1.Text = "scope1";
            displayViewBackground8.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayTitle2.Background = displayViewBackground8;
            displayTitle2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 27, 1);
            displayTitle2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("displayTitle2.InternalData")));
            displayTitle2.Text = "Scope";
            displayViewSize6.Size = ((uint)(100u));
            displayTitle2.ViewSize = displayViewSize6;
            this.scope1.Title = displayTitle2;
            displayToolBar2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            displayToolBar2.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayToolBarButtons2.Copy = displayToolBarButton21;
            displayToolBarButtons2.Hold = displayToolBarButton22;
            displayToolBarButtons2.Print = displayToolBarButton23;
            displayToolBarButtons2.Save = displayToolBarButton24;
            displayToolBarButtons2.Setup = displayToolBarButton25;
            displayToolBarButtons2.XYZoomOn = displayToolBarButton26;
            displayToolBarButtons2.ZoomIn = displayToolBarButton27;
            displayToolBarButtons2.ZoomMode = displayToolBarButton28;
            displayToolBarButtons2.ZoomNext = displayToolBarButton29;
            displayToolBarButtons2.ZoomOff = displayToolBarButton30;
            displayToolBarButtons2.ZoomOut = displayToolBarButton31;
            displayToolBarButtons2.ZoomPrevious = displayToolBarButton32;
            displayToolBar2.Buttons = displayToolBarButtons2;
            displayToolBar2.Cursor = System.Windows.Forms.Cursors.Default;
            displayToolBar2.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            displayToolBar2.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar2.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar2.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            displayToolBar2.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar2.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            toolBarPosition2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("toolBarPosition2.InternalData")));
            displayToolBar2.Position = toolBarPosition2;
            this.scope1.ToolBar = displayToolBar2;
            displayTrails2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            displayTrails2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 0);
            this.scope1.Trails = displayTrails2;
            displayTitleLabel3.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            scopeXAxis2.AxisLabel = displayTitleLabel3;
            displayViewBackground9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeXAxis2.Background = displayViewBackground9;
            viewButtonSettings3.Cursor = System.Windows.Forms.Cursors.Default;
            viewButtonSettings3.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings3.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            viewButtonSettings3.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings3.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeXAxis2.Button = viewButtonSettings3;
            scopeXAxis2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            scopeXAxis2.CursorSettings = displayAxisCursorSettings3;
            vclPen9.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            vclPen9.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen9.InternalData")));
            displayGridLineSettings7.Pen = vclPen9;
            displayGridDirectionalLinesSettings3.Lines = displayGridLineSettings7;
            vclPen10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            vclPen10.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen10.InternalData")));
            displayGridLineSettings8.Pen = vclPen10;
            displayGridDirectionalLinesSettings3.ZeroLine = displayGridLineSettings8;
            scopeXAxis2.DataView = displayGridDirectionalLinesSettings3;
            scopeXAxis2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 0);
            axisFormat3.Precision = 3;
            scopeXAxis2.Format = axisFormat3;
            scopeXAxis2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeXAxis2.InternalData")));
            ticksStart3.StartFrom = 0D;
            majorTicks3.StartFrom = ticksStart3;
            majorTicks3.Step = 10D;
            scopeXAxis2.MajorTicks = majorTicks3;
            maxAxisValue3.DataValue = 1024D;
            displayOptionalValue13.Enabled = false;
            displayOptionalValue13.Value = 1000D;
            displayValueRange7.High = displayOptionalValue13;
            displayOptionalValue14.Enabled = false;
            displayOptionalValue14.Value = -1000D;
            displayValueRange7.Low = displayOptionalValue14;
            maxAxisValue3.Range = displayValueRange7;
            basicAxisValue5.Value = 1024D;
            maxAxisValue3.Tick = basicAxisValue5;
            maxAxisValue3.Value = 1024D;
            scopeXAxis2.Max = maxAxisValue3;
            scopeMaxSample2.Value = ((uint)(1024u));
            scopeXAxis2.MaxSample = scopeMaxSample2;
            axisValue3.DataValue = 0D;
            displayOptionalValue15.Enabled = false;
            displayOptionalValue15.Value = 1000D;
            displayValueRange8.High = displayOptionalValue15;
            displayOptionalValue16.Enabled = false;
            displayOptionalValue16.Value = -1000D;
            displayValueRange8.Low = displayOptionalValue16;
            axisValue3.Range = displayValueRange8;
            basicAxisValue6.Value = 0D;
            axisValue3.Tick = basicAxisValue6;
            axisValue3.Value = 0D;
            scopeXAxis2.Min = axisValue3;
            scopeXAxis2.MinorTicks = minorTicks3;
            axisToolBar3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar3.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            axisToolBarButtons3.ZoomIn = displayToolBarButton33;
            axisToolBarButtons3.ZoomOff = displayToolBarButton34;
            axisToolBarButtons3.ZoomOneDir = displayToolBarButton35;
            axisToolBarButtons3.ZoomOut = displayToolBarButton36;
            axisToolBar3.Buttons = axisToolBarButtons3;
            axisToolBar3.Cursor = System.Windows.Forms.Cursors.Default;
            axisToolBar3.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar3.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar3.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar3.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar3.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar3.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeXAxis2.ToolBar = axisToolBar3;
            scopeXAxis2.TrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeXAxis2.UnitScale = scopeXAxisUnitScale2;
            displayViewSize7.Size = ((uint)(100u));
            scopeXAxis2.ViewSize = displayViewSize7;
            displayOptionalValue17.Enabled = false;
            displayOptionalValue17.Value = 100000000D;
            displayValueRange9.High = displayOptionalValue17;
            displayOptionalValue18.Enabled = true;
            displayOptionalValue18.Value = 1E-07D;
            displayValueRange9.Low = displayOptionalValue18;
            displayAxisZoom3.Range = displayValueRange9;
            scopeXAxis2.Zooming = displayAxisZoom3;
            scopeXAxis2.ZoomPin = statePin3;
            this.scope1.XAxis = scopeXAxis2;
            this.scope1.XInputPins = pinList4;
            scopeAutoScaling2.MaxHistory = ((uint)(20u));
            scopeAutoScalingSpace3.Space = ((uint)(20u));
            scopeAutoScalingSpace3.Threshold = ((uint)(10u));
            scopeAutoScaling2.SpaceAbove = scopeAutoScalingSpace3;
            scopeAutoScalingSpace4.Space = ((uint)(20u));
            scopeAutoScalingSpace4.Threshold = ((uint)(10u));
            scopeAutoScaling2.SpaceBelow = scopeAutoScalingSpace4;
            scopeYAxis2.AutoScaling = scopeAutoScaling2;
            displayTitleLabel4.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 17, 1);
            displayTitleLabel4.Text = "Y Axis";
            scopeYAxis2.AxisLabel = displayTitleLabel4;
            displayViewBackground10.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeYAxis2.Background = displayViewBackground10;
            viewButtonSettings4.Cursor = System.Windows.Forms.Cursors.Default;
            viewButtonSettings4.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings4.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            viewButtonSettings4.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings4.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeYAxis2.Button = viewButtonSettings4;
            scopeYAxis2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            scopeYAxis2.CursorSettings = displayAxisCursorSettings4;
            vclPen11.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            vclPen11.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen11.InternalData")));
            displayGridLineSettings9.Pen = vclPen11;
            displayGridDirectionalLinesSettings4.Lines = displayGridLineSettings9;
            vclPen12.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            vclPen12.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen12.InternalData")));
            displayGridLineSettings10.Pen = vclPen12;
            displayGridDirectionalLinesSettings4.ZeroLine = displayGridLineSettings10;
            scopeYAxis2.DataView = displayGridDirectionalLinesSettings4;
            scopeYAxis2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 0);
            axisFormat4.Precision = 3;
            scopeYAxis2.Format = axisFormat4;
            scopeYAxis2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeYAxis2.InternalData")));
            ticksStart4.StartFrom = 0D;
            majorTicks4.StartFrom = ticksStart4;
            majorTicks4.Step = 10D;
            scopeYAxis2.MajorTicks = majorTicks4;
            maxAxisValue4.DataValue = 1000D;
            displayOptionalValue19.Enabled = false;
            displayOptionalValue19.Value = 1000D;
            displayValueRange10.High = displayOptionalValue19;
            displayOptionalValue20.Enabled = false;
            displayOptionalValue20.Value = -1000D;
            displayValueRange10.Low = displayOptionalValue20;
            maxAxisValue4.Range = displayValueRange10;
            basicAxisValue7.Value = 0D;
            maxAxisValue4.Tick = basicAxisValue7;
            maxAxisValue4.Value = 1000D;
            scopeYAxis2.Max = maxAxisValue4;
            axisValue4.DataValue = -1000D;
            displayOptionalValue21.Enabled = false;
            displayOptionalValue21.Value = 1000D;
            displayValueRange11.High = displayOptionalValue21;
            displayOptionalValue22.Enabled = false;
            displayOptionalValue22.Value = -1000D;
            displayValueRange11.Low = displayOptionalValue22;
            axisValue4.Range = displayValueRange11;
            basicAxisValue8.Value = 0D;
            axisValue4.Tick = basicAxisValue8;
            axisValue4.Value = -1000D;
            scopeYAxis2.Min = axisValue4;
            scopeYAxis2.MinorTicks = minorTicks4;
            axisToolBar4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar4.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            axisToolBarButtons4.ZoomIn = displayToolBarButton37;
            axisToolBarButtons4.ZoomOff = displayToolBarButton38;
            axisToolBarButtons4.ZoomOneDir = displayToolBarButton39;
            axisToolBarButtons4.ZoomOut = displayToolBarButton40;
            axisToolBar4.Buttons = axisToolBarButtons4;
            axisToolBar4.Cursor = System.Windows.Forms.Cursors.Default;
            axisToolBar4.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar4.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar4.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar4.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar4.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar4.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeYAxis2.ToolBar = axisToolBar4;
            scopeYAxis2.TrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayViewSize8.Size = ((uint)(100u));
            scopeYAxis2.ViewSize = displayViewSize8;
            displayOptionalValue23.Enabled = false;
            displayOptionalValue23.Value = 100000000D;
            displayValueRange12.High = displayOptionalValue23;
            displayOptionalValue24.Enabled = true;
            displayOptionalValue24.Value = 1E-07D;
            displayValueRange12.Low = displayOptionalValue24;
            displayAxisZoom4.Range = displayValueRange12;
            scopeYAxis2.Zooming = displayAxisZoom4;
            scopeYAxis2.ZoomPin = statePin4;
            this.scope1.YAxis = scopeYAxis2;
            displayZoom2.SelectionColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.scope1.Zooming = displayZoom2;
            // 
            // textBox1
            // 
            this.textBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.textBox1.BackColor = System.Drawing.SystemColors.MenuText;
            this.textBox1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.textBox1.ForeColor = System.Drawing.SystemColors.Window;
            this.textBox1.Location = new System.Drawing.Point(676, 151);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(86, 22);
            this.textBox1.TabIndex = 4;
            // 
            // button1
            // 
            this.button1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.button1.Location = new System.Drawing.Point(676, 99);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(86, 23);
            this.button1.TabIndex = 3;
            this.button1.Text = "Peak";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // UI_FrequencySpectrum
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.textBox1);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.panelControl1);
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "UI_FrequencySpectrum";
            this.Size = new System.Drawing.Size(766, 395);
            ((System.ComponentModel.ISupportInitialize)(this.panelControl1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.scope1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private DevExpress.XtraEditors.PanelControl panelControl1;
        private Mitov.PlotLab.Scope scope1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Button button1;



    }
}
